  # Configure what service plugins are used by Umlaut. This skeleton file
  # has been generated into your app to help you get started. 
  #
  # If a service has "disabled:true", it's currently turned off. 
  #
  # Some services require local api key or connection details as config.
  # Most services take other options for custom configuration too, not
  # all options are neccesarily listed as examples here, see source
  # or source-generated docs for more info.   

  # The services in the 'default' group are loaded every time. 
  # You can optionally create other groups of services, that can be loaded
  # by URL query params, or based on other request params. More info?

default:
    services:
      
      # SFX has pubmed lookup built in, so this service not generally
      # needed with SFX, but included here as an example of it's availability
      Pubmed:
        disabled: true
        priority: 0
      
      # Priority 3
      
      SFX:
        type: Sfx
        disabled: false
        display_name: FindIt
        base_url: http://sfx.kb.dk/sfx_local
        priority: 3


      SFXRSI:
        type: SfxRsi
        disabled: true
        base_url: http://sfx.kb.dk/sfx_local/cgi/core/rsi/rsi.cgi
        priority: 3
      # First half of Amazon, run in foreground, get metadata and cover images.
      Amazon:
        disabled: true
        display_name: Amazon.com
        type: Amazon
        url: http://webservices.amazon.com/onca/xml
        api_key: "NEED_API_KEY"
        secret_key: "NEED_SECRET_KEY"
        associate_tag: "NEED_ASSOCIATE_ID"
        priority: 3
        service_types:
          - abstract
          - referent_enhance
          - cover_image


      RexSearch:
        type: RexSearch
        disabled: false
        priority: c
        url: http://rex.kb.dk/primo_library/libweb/action/dlSearch.do?institution=KGL&vid=KGL&search_scope=KGL&group=GUEST&query=any,contains,%{issn/isbn}%{+OR+}(%{title}%)
        display_name: Det Kongelige Bibliotek
        display_text: search_in_rex

      BibliotekDKSearch:
        type: ExternalSearch
        disabled: false
        priority: c
        url: http://bibliotek.dk/da/search/work/%{issn/isbn}?sort=date_descending&qe[year.op][0]=year_eq&page_id=bibdk_frontpage#content
        display_name: Bibliotek.dk
        display_text: search_in_bibliotek

      # Priority c  : Background          

      # Suggest that any background services that may produce `fulltext` responses
      # be put in the same bg wave, to increase perceived responsiveness
      # by ending the spinner in the fulltext area.
      
      # Second half of Amazon. It's Slow to lookup highlighted_link and search_inside
      # availability, so we do it in a bg wave.  
      Amazon_bg:
        type: Amazon
        disabled: true        
        api_key: "NEED_API_KEY"
        secret_key: "NEED_SECRET_KEY"
        associate_tag: "NEED_ASSOCIATE_ID"
        priority: c        
        make_aws_call: false
        service_types:
          - highlighted_link
          - search_inside
          - excerpts          
      
      CoverThing:
        type: CoverThing
        disabled: true        
        developer_key: YOUR_LT_KEY
        priority: c
        # Pre-empted by says if we already have a cover_image response
        # from somewhere else that runs earlier, don't run this. 
        preempted_by:
          existing_type: cover_image
          
      ElsevierCover:
        type: ElsevierCover
        priority: 1
        
      UlrichsCover:
        type: UlrichsCover
        priority: 1
        
      OpenLibraryCover:
        type: OpenLibraryCover
        priority: 1
        disabled: false
          
      GoogleBookSearch:
        type: GoogleBookSearch
        disabled: true
        priority: c        
        api_key: 'YOUR_GBS_API_KEY'                
        
      InternetArchive:
        display_name: the Internet Archive
        type: InternetArchive
        priority: c
        # disable audio results? uncomment:
        #num_results_for_types:
        #  audio: 0

      HathiTrust:
        type: HathiTrust
        priority: c
        disabled: true
        # Uncomment to link through this 'internal' URL instead
        # of following permalinks. jrochkind does this to use
        # a WAYFless shibboleth login with EZProxy. 
        #direct_link_base: 'https://babel.hathitrust.org/shcgi/'
        #
        # This next says:
        # Don't add HathiTrust fulltext if there's already a
        # GoogleBookSearch fulltext. Still add other HT response
        # types. 
        preempted_by:
          self_type: fulltext
          existing_service: GoogleBookSearch
          existing_type: fulltext
          
      Bx:
        display_name: bX
        type: Bx
        token: tokentokentoken
        disabled: false
        priority: c
 
        

      
      # Priority d

      # You might be able to pack a lot of these in 'c' too, simultaneously.
      # But to avoid trying to do too much at once, we put most 'see also'
      # type services later, in 'd'. 

      Ulrichs:
        display_name: "Ulrich's Directory"
        type: UlrichsLink
        disabled: true
        priority: d
        
      IsbnDb:
        display_name: isbndb.com
        disabled: true
        type: IsbnDb
        priority: d
        access_key: YOUR_ISBNDB_ACCESS_KEY
                
      EmailExport:
        type: EmailExport
        disabled: true
        priority: d
        
      TxtHoldingExport:
        type: TxtHoldingExport
        priority: d

      ScopusCitations:
        type: Scopus
        disabled: true
        priority: d
        json_api_key: YOUR_SCOPUS_API_KEY
        partner_id: YOUR_SCOPUS_PARTNER_ID
        link_salt_key: "YOUR_SCOPUS_LINK_SALT_KEY"
        
      # Web of Knowledge API has no api key, but your
      # IP needs to be registered with them. See source docs
      # for how. 
      IsiCitations:
        type: Isi
        disabled: true
        priority: d
        
      # Thomson JCR LAMR api has no api key, but your
      # IP needs to be registered with them. Same registraiton
      # as for ISI WoK generally.
      Jcr:
        type: Jcr
        disabled: true
        priority: d
      
        

      # Worldcat scraper can be quite slow, move it to wave 'd' to avoid
      # holding up wave 'c'
      Worldcat:
        display_name: OCLC Worldcat.org
        type: Worldcat
        disabled: true
        priority: d
        # suppress_precheck says don't actually screen-scrape to
        # see if the link is good, just link blindly. Mostly works
        # for WorldCat, avoids the performance hit. 
        suppress_precheck: true
      
      
      WorldcatIdentities:
        type: WorldcatIdentities
        priority: d
        # Turn off certain response types:
        #note_types: false
        #wikipedia_link: false
        #openurl_widely_held: false
        #require_identifier: true
      
      
      # GPO is kind of experimental, it doesn't work great, but IF an 
      # OpenURL includes a sudoc call number or other GPO identifiers,
      # will try to link to full text via GPO catalog scrape. 
      Gpo:
        type: Gpo
        disabled: true
        priority: e
        #preempted_by:
        #  - existing_type: fulltext
        #  - existing_type: fulltext_title_level


      ####
      # Link out filters: Effect what happens when a user clicks
      # on an Umlaut link to a third party source. Link out filters
      # can operate to change where link goes or execute side effects
      # on click. 
      ####

      # Redirect outgoing links through EZProxy                
      EZProxy:
        type: Ezproxy
        disabled: false
        task: link_out_filter  
        proxy_server:  ep.fjernadgang.kb.dk
        # By default, will pre-check with EZProxy api and
        # only send links through EZProxy that are proxyable.
        # requires proxy_password to be set. 
        # optionally, set precheck_with_api false, and the EZProxy
        # api won't be used, ALL links go through EZProxy. You may
        # have EZProxy itself set to transparently redirect non-proxyable
        # URLs back to non-proxied version.
        #
        precheck_with_api: true
        priority: 5
        proxy_password: YOUR_EZPROXY_API_PWD
        # Want to exclude certain hostnames from being directed through EZProxy?
        # list them in array here:
        #exclude: [ host.unversity.edu, otherhost.somewhere.com]
        exclude: [ rex.kb.dk, bibliotek.dk]
        
group1:
  default: false
  services:
    SFX:
      type: Sfx
      disabled: false
      display_name: Phobos
      base_url: http://sfx-test-01.kb.dk:3410/sfx_local
      priority: 3

group2:
  default: false
  services:
      SFXRSI:
        type: SfxRsi
        disabled: false
        base_url: http://sfx.kb.dk/sfxtst41/cgi/core/rsi/rsi.cgi
        priority: 3
